/**
 * lib/agent-database.ts — Mock agent roster for matching during development.
 * Every object fully satisfies the Agent type from types/agent.ts.
 * In production this is replaced by a real database query.
 */

import type { Agent } from '@/types/agent';

const MARKET_MEDIAN_DOM     = 28;
const MARKET_SP_LP          = 99.4;
const MARKET_PRICE_RED_RATE = 14.3;
const MARKET_FALL_THROUGH   = 7.8;

// ── Agent 1: Sarah Chen — Compass, Healdsburg luxury specialist ────────────────
// (imported from placeholder.ts for single source of truth)
export { placeholderAgent as sarahChen } from '@/app/agents/[id]/placeholder';

// ── Agent 2: Marcus Rivera — Keller Williams, Santa Rosa first-time buyer specialist
const marcusRivera: Agent = {
  id:                 'marcus-rivera-002',
  name:               'Marcus Rivera',
  headshotUrl:        'https://randomuser.me/api/portraits/men/32.jpg',
  headshotSource:     'zillow',
  brokerageName:      'Keller Williams North Bay',
  brokerageLogoUrl:   null,
  licenseNumber:      '02047821',
  licenseType:        'Salesperson',
  licenseStatus:      'Active',
  licenseIssueDate:   '2010-06-22',
  primaryCounty:      'Sonoma',
  primaryCity:        'Santa Rosa',
  languages:          ['English', 'Spanish'],

  provnScore:         81,
  provnLetterGrade:   'B+',

  salePriceToListRatio:       101.4,
  salePriceToListRatioMarket: MARKET_SP_LP,
  avgDaysOnMarket:            18,
  marketMedianDaysOnMarket:   MARKET_MEDIAN_DOM,
  priceReductionRate:         9.8,
  marketPriceReductionRate:   MARKET_PRICE_RED_RATE,
  fallThroughRate:            5.1,
  marketFallThroughRate:      MARKET_FALL_THROUGH,
  totalCareerTransactions:    194,
  totalCareerVolume:          112_000_000,
  volumeLast12Months:         18_400_000,
  volumePrior12Months:        15_200_000,

  propertyOwnershipVerified:   true,
  propertiesOwnedCount:        2,
  portfolioValueMin:           780_000,
  portfolioValueMax:           960_000,
  yearsOfContinuousOwnership:  9,
  battleScar:                  null,

  autoBadges: [
    { category: 'Residential Under $1M', transactionCount: 142 },
    { category: 'First-Time Buyers',     transactionCount: 63  },
    { category: 'Condos / Townhomes',    transactionCount: 29  },
    { category: 'New Construction',      transactionCount: 11  },
  ],
  manualBadges: [
    { label: 'Fluent: Spanish', verificationSource: 'Verified by Provn', detail: 'Native speaker' },
  ],

  zipSpecializations: [
    { zip: '95401', label: 'Santa Rosa',    percentage: 42 },
    { zip: '95404', label: 'Santa Rosa NE', percentage: 22 },
    { zip: '95492', label: 'Windsor',       percentage: 18 },
    { zip: '94928', label: 'Rohnert Park',  percentage: 11 },
    { zip: '94931', label: 'Cotati',        percentage:  7 },
  ],
  offMarketDealCount:  4,
  activeInCountySince: 2010,

  writingStyleSummary:  'Clear, instructional language with frequent process explanations — well suited for first-time buyers navigating the transaction.',
  responseGrade:        'Same day',
  consistencyRating:    'Highly consistent',
  clientTypeMatch:      'Best matched for first-time buyers and move-up buyers in the $400K–$900K range across Santa Rosa and Windsor.',

  reviewPlatforms: [
    { platform: 'Google',      score: 4.8, reviewCount: 62, maxScore: 5 },
    { platform: 'Zillow',      score: 4.8, reviewCount: 41, maxScore: 5 },
    { platform: 'Realtor.com', score: 4.7, reviewCount: 15, maxScore: 5 },
  ],
  weightedCompositeScore:    4.78,
  totalVerifiedReviewCount:  118,
  mostRecentReviewDate:      '2026-04-18',
  highlightQuote:            'Marcus was patient throughout the entire process and explained every step. As first-time buyers, we were nervous — he made the whole thing feel manageable.',
  reviewKeywordThemes:       ['Patience', 'First-Time Buyers', 'Responsiveness'],
  postCloseSurveyScore:      4.8,

  radarData: {
    fiveStarReviews: {
      score: 78, percentile: 74, countyMedian: 43, top10Threshold: 85,
      rawValue: '79 five-star reviews across 3 platforms',
      plainEnglish: '79 five-star reviews with a 4.78 composite score',
    },
    localMarketExpertise: {
      score: 72, percentile: 68, countyMedian: 36, top10Threshold: 84,
      rawValue: '5 active zip codes · strong Santa Rosa concentration',
      plainEnglish: 'Deep local expertise across Santa Rosa and Windsor',
    },
    careerVolume: {
      score: 58, percentile: 62, countyMedian: 40, top10Threshold: 88,
      rawValue: '$112M career sales volume',
      plainEnglish: '$112M in career sales — top 38% of Sonoma County agents',
    },
    skinInTheGame: {
      score: 62, percentile: 60, countyMedian: 31, top10Threshold: 80,
      rawValue: '2 verified properties · 9 years continuous ownership',
      plainEnglish: '2 personally owned Sonoma County properties',
    },
    successfulOutcomes: {
      score: 82, percentile: 78, countyMedian: 55, top10Threshold: 87,
      rawValue: '88% of all listings taken eventually sold',
      plainEnglish: 'Sold 88% of every listing taken — 15 points above county average',
    },
    expertiseDepth: {
      score: 68, percentile: 65, countyMedian: 38, top10Threshold: 86,
      rawValue: '194 weighted transaction points · 4 specialty categories',
      plainEnglish: '4 specialty types including first-time buyers and new construction',
    },
  },

  marketConsistency: {
    monthlyActivity: [
      { year: 2023, month:  6, status: 'closed'  },
      { year: 2023, month:  7, status: 'closed'  },
      { year: 2023, month:  8, status: 'active'  },
      { year: 2023, month:  9, status: 'closed'  },
      { year: 2023, month: 10, status: 'closed'  },
      { year: 2023, month: 11, status: 'active'  },
      { year: 2023, month: 12, status: 'active'  },
      { year: 2024, month:  1, status: 'active'  },
      { year: 2024, month:  2, status: 'none'    },
      { year: 2024, month:  3, status: 'closed'  },
      { year: 2024, month:  4, status: 'closed'  },
      { year: 2024, month:  5, status: 'closed'  },
      { year: 2024, month:  6, status: 'closed'  },
      { year: 2024, month:  7, status: 'closed'  },
      { year: 2024, month:  8, status: 'active'  },
      { year: 2024, month:  9, status: 'closed'  },
      { year: 2024, month: 10, status: 'closed'  },
      { year: 2024, month: 11, status: 'active'  },
      { year: 2024, month: 12, status: 'active'  },
      { year: 2025, month:  1, status: 'active'  },
      { year: 2025, month:  2, status: 'closed'  },
      { year: 2025, month:  3, status: 'closed'  },
      { year: 2025, month:  4, status: 'closed'  },
      { year: 2025, month:  5, status: 'closed'  },
      { year: 2025, month:  6, status: 'closed'  },
      { year: 2025, month:  7, status: 'closed'  },
      { year: 2025, month:  8, status: 'active'  },
      { year: 2025, month:  9, status: 'closed'  },
      { year: 2025, month: 10, status: 'closed'  },
      { year: 2025, month: 11, status: 'active'  },
      { year: 2025, month: 12, status: 'active'  },
      { year: 2026, month:  1, status: 'closed'  },
      { year: 2026, month:  2, status: 'closed'  },
      { year: 2026, month:  3, status: 'closed'  },
      { year: 2026, month:  4, status: 'closed'  },
      { year: 2026, month:  5, status: 'active'  },
    ],
    longestGapMonths:          3,
    avgTransactionsLast3Years: 14,
    listingsTakenLast12:       18,
    listingsClosedLast12:      14,
    expiredToCompetitorPct:    12,
    lastClosingDate:           '2026-04-18',
  },

  activePriceBandLow:    400_000,
  activePriceBandHigh:   950_000,
  activePriceBandCount:  92,
  mostRecentSaleDate:    '2026-04-18',
  mostRecentSalePrice:   618_000,
  mostRecentSaleCity:    'Santa Rosa',
  disciplinaryRecord:    'clean',
  soloOrTeam:            'solo',
  activeListingsCount:   3,
  highestSalePrice:      1_100_000,
  yearsInLocalMarket:    28,
  brokerageTenureYears:  7,

  isPremium:            false,
  introVideoUrl:        null,
  winStories:           [],
  featuredNeighborhood: 'Santa Rosa',
};

// ── Agent 3: Jennifer Park — Sotheby's, Sonoma / Napa cross-county expert ─────
const jenniferPark: Agent = {
  id:                 'jennifer-park-003',
  name:               'Jennifer Park',
  headshotUrl:        'https://randomuser.me/api/portraits/women/68.jpg',
  headshotSource:     'zillow',
  brokerageName:      "Sotheby's International Realty",
  brokerageLogoUrl:   null,
  licenseNumber:      '01884193',
  licenseType:        'Broker',
  licenseStatus:      'Active',
  licenseIssueDate:   '2005-09-11',
  primaryCounty:      'Sonoma',
  primaryCity:        'Sonoma',
  languages:          ['English', 'Korean'],

  provnScore:         87,
  provnLetterGrade:   'A',

  salePriceToListRatio:       102.1,
  salePriceToListRatioMarket: MARKET_SP_LP,
  avgDaysOnMarket:            15,
  marketMedianDaysOnMarket:   MARKET_MEDIAN_DOM,
  priceReductionRate:         8.4,
  marketPriceReductionRate:   MARKET_PRICE_RED_RATE,
  fallThroughRate:            4.2,
  marketFallThroughRate:      MARKET_FALL_THROUGH,
  totalCareerTransactions:    241,
  totalCareerVolume:          298_000_000,
  volumeLast12Months:         34_100_000,
  volumePrior12Months:        28_600_000,

  propertyOwnershipVerified:   true,
  propertiesOwnedCount:        3,
  portfolioValueMin:           2_100_000,
  portfolioValueMax:           2_800_000,
  yearsOfContinuousOwnership:  12,
  battleScar:                  '"In 2021, a bidding war I was managing fell apart when the lender missed an appraisal deadline. The buyers were devastated. I stayed through three weeks of renegotiation and we closed at a price that was still acceptable to both sides. Now I require written appraisal timelines from every lender before we submit an offer."',

  autoBadges: [
    { category: 'Luxury ($1M+)',        transactionCount: 118 },
    { category: 'Investment / 1031',    transactionCount:  22 },
    { category: 'Vineyard / Land',      transactionCount:  14 },
    { category: 'Relocation',           transactionCount:  19 },
    { category: 'New Construction',     transactionCount:   9 },
  ],
  manualBadges: [
    { label: 'Certified Luxury Home Marketing Specialist', verificationSource: 'Verified by Provn' },
    { label: 'Fluent: Korean',                            verificationSource: 'Verified by Provn', detail: 'Native speaker' },
  ],

  zipSpecializations: [
    { zip: '95476', label: 'Sonoma',     percentage: 38 },
    { zip: '94952', label: 'Petaluma',   percentage: 24 },
    { zip: '95472', label: 'Sebastopol', percentage: 16 },
    { zip: '94558', label: 'Napa',       percentage: 14 },
    { zip: '95401', label: 'Santa Rosa', percentage:  8 },
  ],
  offMarketDealCount:  29,
  activeInCountySince: 2005,

  writingStyleSummary:  'Lifestyle-forward copy with strong emotional resonance — language patterns correlate with faster DOM on listings over $1.2M.',
  responseGrade:        'Under 1 hour',
  consistencyRating:    'Highly consistent',
  clientTypeMatch:      'Best matched for luxury buyers and sellers in the $900K–$3M range across Sonoma Valley and Napa Valley.',

  reviewPlatforms: [
    { platform: 'Google',      score: 4.9, reviewCount: 72, maxScore: 5 },
    { platform: 'Zillow',      score: 4.8, reviewCount: 58, maxScore: 5 },
    { platform: 'Realtor.com', score: 4.8, reviewCount: 29, maxScore: 5 },
  ],
  weightedCompositeScore:    4.85,
  totalVerifiedReviewCount:  159,
  mostRecentReviewDate:      '2026-05-10',
  highlightQuote:            'Jennifer found us a property that was never publicly listed. We closed at a price we never thought possible and skipped the bidding wars entirely.',
  reviewKeywordThemes:       ['Local Knowledge', 'Off-Market Access', 'Negotiation'],
  postCloseSurveyScore:      4.9,

  radarData: {
    fiveStarReviews: {
      score: 86, percentile: 83, countyMedian: 43, top10Threshold: 85,
      rawValue: '131 five-star reviews across 3 platforms',
      plainEnglish: '131 five-star reviews with a 4.85 composite score',
    },
    localMarketExpertise: {
      score: 85, percentile: 82, countyMedian: 36, top10Threshold: 84,
      rawValue: '5 active zip codes · dual county coverage',
      plainEnglish: 'Cross-county expertise in 5 Sonoma and Napa zip codes',
    },
    careerVolume: {
      score: 82, percentile: 80, countyMedian: 40, top10Threshold: 88,
      rawValue: '$298M career sales volume',
      plainEnglish: '$298M in career sales — top 20% of active Sonoma County agents',
    },
    skinInTheGame: {
      score: 78, percentile: 76, countyMedian: 31, top10Threshold: 80,
      rawValue: '3 verified properties · 12 years continuous ownership',
      plainEnglish: '3 personally owned properties across Sonoma County',
    },
    successfulOutcomes: {
      score: 88, percentile: 84, countyMedian: 55, top10Threshold: 87,
      rawValue: '91% of all listings taken eventually sold',
      plainEnglish: 'Sold 91% of every listing taken — 18 points above county average',
    },
    expertiseDepth: {
      score: 88, percentile: 86, countyMedian: 38, top10Threshold: 86,
      rawValue: '384 weighted transaction points · 5 specialty categories',
      plainEnglish: '5 specialty types including luxury, 1031 exchanges, and relocation',
    },
  },

  marketConsistency: {
    monthlyActivity: [
      { year: 2023, month:  6, status: 'closed'  },
      { year: 2023, month:  7, status: 'closed'  },
      { year: 2023, month:  8, status: 'closed'  },
      { year: 2023, month:  9, status: 'active'  },
      { year: 2023, month: 10, status: 'closed'  },
      { year: 2023, month: 11, status: 'active'  },
      { year: 2023, month: 12, status: 'active'  },
      { year: 2024, month:  1, status: 'closed'  },
      { year: 2024, month:  2, status: 'closed'  },
      { year: 2024, month:  3, status: 'closed'  },
      { year: 2024, month:  4, status: 'closed'  },
      { year: 2024, month:  5, status: 'closed'  },
      { year: 2024, month:  6, status: 'closed'  },
      { year: 2024, month:  7, status: 'closed'  },
      { year: 2024, month:  8, status: 'closed'  },
      { year: 2024, month:  9, status: 'active'  },
      { year: 2024, month: 10, status: 'closed'  },
      { year: 2024, month: 11, status: 'closed'  },
      { year: 2024, month: 12, status: 'active'  },
      { year: 2025, month:  1, status: 'closed'  },
      { year: 2025, month:  2, status: 'closed'  },
      { year: 2025, month:  3, status: 'closed'  },
      { year: 2025, month:  4, status: 'closed'  },
      { year: 2025, month:  5, status: 'closed'  },
      { year: 2025, month:  6, status: 'closed'  },
      { year: 2025, month:  7, status: 'closed'  },
      { year: 2025, month:  8, status: 'closed'  },
      { year: 2025, month:  9, status: 'active'  },
      { year: 2025, month: 10, status: 'closed'  },
      { year: 2025, month: 11, status: 'closed'  },
      { year: 2025, month: 12, status: 'active'  },
      { year: 2026, month:  1, status: 'closed'  },
      { year: 2026, month:  2, status: 'closed'  },
      { year: 2026, month:  3, status: 'closed'  },
      { year: 2026, month:  4, status: 'closed'  },
      { year: 2026, month:  5, status: 'closed'  },
    ],
    longestGapMonths:          2,
    avgTransactionsLast3Years: 17,
    listingsTakenLast12:       20,
    listingsClosedLast12:      17,
    expiredToCompetitorPct:    9,
    lastClosingDate:           '2026-05-10',
  },

  activePriceBandLow:    650_000,
  activePriceBandHigh:   2_500_000,
  activePriceBandCount:  89,
  mostRecentSaleDate:    '2026-05-10',
  mostRecentSalePrice:   1_240_000,
  mostRecentSaleCity:    'Sonoma',
  disciplinaryRecord:    'clean',
  soloOrTeam:            'solo',
  activeListingsCount:   5,
  highestSalePrice:      4_200_000,
  yearsInLocalMarket:    35,
  brokerageTenureYears:  11,

  isPremium:            false,
  introVideoUrl:        null,
  winStories:           [],
  featuredNeighborhood: 'Sonoma Valley',
};

// ── Agent 4: David Okafor — RE/MAX Gold, Santa Rosa mid-market ────────────────
const davidOkafor: Agent = {
  id:                 'david-okafor-004',
  name:               'David Okafor',
  headshotUrl:        'https://randomuser.me/api/portraits/men/75.jpg',
  headshotSource:     'zillow',
  brokerageName:      'RE/MAX Gold',
  brokerageLogoUrl:   null,
  licenseNumber:      '02118347',
  licenseType:        'Salesperson',
  licenseStatus:      'Active',
  licenseIssueDate:   '2013-02-08',
  primaryCounty:      'Sonoma',
  primaryCity:        'Santa Rosa',
  languages:          ['English'],

  provnScore:         79,
  provnLetterGrade:   'B+',

  salePriceToListRatio:       100.8,
  salePriceToListRatioMarket: MARKET_SP_LP,
  avgDaysOnMarket:            21,
  marketMedianDaysOnMarket:   MARKET_MEDIAN_DOM,
  priceReductionRate:         10.2,
  marketPriceReductionRate:   MARKET_PRICE_RED_RATE,
  fallThroughRate:            6.1,
  marketFallThroughRate:      MARKET_FALL_THROUGH,
  totalCareerTransactions:    178,
  totalCareerVolume:           98_000_000,
  volumeLast12Months:         14_200_000,
  volumePrior12Months:        12_800_000,

  propertyOwnershipVerified:   false,
  propertiesOwnedCount:        1,
  portfolioValueMin:           480_000,
  portfolioValueMax:           480_000,
  yearsOfContinuousOwnership:  4,
  battleScar:                  null,

  autoBadges: [
    { category: 'Residential Under $1M', transactionCount: 144 },
    { category: 'Condos / Townhomes',    transactionCount:  28 },
    { category: 'Multifamily',           transactionCount:   6 },
  ],
  manualBadges: [],

  zipSpecializations: [
    { zip: '95401', label: 'Santa Rosa',    percentage: 48 },
    { zip: '95404', label: 'Santa Rosa NE', percentage: 20 },
    { zip: '95492', label: 'Windsor',       percentage: 16 },
    { zip: '94928', label: 'Rohnert Park',  percentage:  9 },
    { zip: '94952', label: 'Petaluma',      percentage:  7 },
  ],
  offMarketDealCount:   3,
  activeInCountySince:  2013,

  writingStyleSummary:  'Straightforward, no-fluff listing descriptions with precise pricing language — aligns with his CMA-first approach.',
  responseGrade:        'Same day',
  consistencyRating:    'Moderate variance',
  clientTypeMatch:      'Best matched for sellers and buyers in the $400K–$850K range in Santa Rosa, Windsor, and Rohnert Park.',

  reviewPlatforms: [
    { platform: 'Google',      score: 4.7, reviewCount: 51, maxScore: 5 },
    { platform: 'Zillow',      score: 4.8, reviewCount: 31, maxScore: 5 },
    { platform: 'Realtor.com', score: 4.7, reviewCount: 12, maxScore: 5 },
  ],
  weightedCompositeScore:    4.74,
  totalVerifiedReviewCount:  94,
  mostRecentReviewDate:      '2026-03-29',
  highlightQuote:            'David priced our home exactly right on day one and we got 4 offers. No guessing, no price drops. He was direct and honest the whole way through.',
  reviewKeywordThemes:       ['Honest Pricing', 'Local Knowledge', 'Communication'],
  postCloseSurveyScore:      4.7,

  radarData: {
    fiveStarReviews: {
      score: 72, percentile: 68, countyMedian: 43, top10Threshold: 85,
      rawValue: '65 five-star reviews across 3 platforms',
      plainEnglish: '65 five-star reviews with a 4.74 composite score',
    },
    localMarketExpertise: {
      score: 74, percentile: 70, countyMedian: 36, top10Threshold: 84,
      rawValue: '5 active zip codes · heavy Santa Rosa concentration',
      plainEnglish: 'Deep Santa Rosa expertise in 5 local zip codes',
    },
    careerVolume: {
      score: 54, percentile: 58, countyMedian: 40, top10Threshold: 88,
      rawValue: '$98M career sales volume',
      plainEnglish: '$98M in career sales — top 42% of Sonoma County agents',
    },
    skinInTheGame: {
      score: 38, percentile: 40, countyMedian: 31, top10Threshold: 80,
      rawValue: '1 owned property · 4 years continuous ownership',
      plainEnglish: '1 personally owned Santa Rosa property',
    },
    successfulOutcomes: {
      score: 78, percentile: 72, countyMedian: 55, top10Threshold: 87,
      rawValue: '88% of all listings taken eventually sold',
      plainEnglish: 'Sold 88% of every listing taken — 15 points above county average',
    },
    expertiseDepth: {
      score: 56, percentile: 54, countyMedian: 38, top10Threshold: 86,
      rawValue: '187 weighted transaction points · 3 specialty categories',
      plainEnglish: '3 specialty types — residential, condo, and multifamily',
    },
  },

  marketConsistency: {
    monthlyActivity: [
      { year: 2023, month:  6, status: 'closed'  },
      { year: 2023, month:  7, status: 'active'  },
      { year: 2023, month:  8, status: 'closed'  },
      { year: 2023, month:  9, status: 'closed'  },
      { year: 2023, month: 10, status: 'active'  },
      { year: 2023, month: 11, status: 'none'    },
      { year: 2023, month: 12, status: 'active'  },
      { year: 2024, month:  1, status: 'active'  },
      { year: 2024, month:  2, status: 'none'    },
      { year: 2024, month:  3, status: 'closed'  },
      { year: 2024, month:  4, status: 'closed'  },
      { year: 2024, month:  5, status: 'closed'  },
      { year: 2024, month:  6, status: 'active'  },
      { year: 2024, month:  7, status: 'closed'  },
      { year: 2024, month:  8, status: 'closed'  },
      { year: 2024, month:  9, status: 'active'  },
      { year: 2024, month: 10, status: 'closed'  },
      { year: 2024, month: 11, status: 'active'  },
      { year: 2024, month: 12, status: 'none'    },
      { year: 2025, month:  1, status: 'active'  },
      { year: 2025, month:  2, status: 'closed'  },
      { year: 2025, month:  3, status: 'closed'  },
      { year: 2025, month:  4, status: 'closed'  },
      { year: 2025, month:  5, status: 'active'  },
      { year: 2025, month:  6, status: 'closed'  },
      { year: 2025, month:  7, status: 'closed'  },
      { year: 2025, month:  8, status: 'none'    },
      { year: 2025, month:  9, status: 'closed'  },
      { year: 2025, month: 10, status: 'closed'  },
      { year: 2025, month: 11, status: 'active'  },
      { year: 2025, month: 12, status: 'none'    },
      { year: 2026, month:  1, status: 'active'  },
      { year: 2026, month:  2, status: 'closed'  },
      { year: 2026, month:  3, status: 'closed'  },
      { year: 2026, month:  4, status: 'active'  },
      { year: 2026, month:  5, status: 'active'  },
    ],
    longestGapMonths:          3,
    avgTransactionsLast3Years: 12,
    listingsTakenLast12:       14,
    listingsClosedLast12:      12,
    expiredToCompetitorPct:    14,
    lastClosingDate:           '2026-03-29',
  },

  activePriceBandLow:    350_000,
  activePriceBandHigh:   900_000,
  activePriceBandCount:  78,
  mostRecentSaleDate:    '2026-03-29',
  mostRecentSalePrice:   647_000,
  mostRecentSaleCity:    'Santa Rosa',
  disciplinaryRecord:    'clean',
  soloOrTeam:            'solo',
  activeListingsCount:   2,
  highestSalePrice:      1_350_000,
  yearsInLocalMarket:    18,
  brokerageTenureYears:  5,

  isPremium:            false,
  introVideoUrl:        null,
  winStories:           [],
  featuredNeighborhood: 'Santa Rosa',
};

// ── Export the full roster ─────────────────────────────────────────────────────
export const AGENT_DATABASE: Agent[] = [
  // Sarah Chen is imported from placeholder.ts — see sarahChen export above.
  // We re-import here so the array is complete.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  require('@/app/agents/[id]/placeholder').placeholderAgent as Agent,
  marcusRivera,
  jenniferPark,
  davidOkafor,
];
